### PR TITLE
fix: support new parse_chat handler

### LINKED ISSUE #62: Does not support new style http adapters.
As of v17.27.0 the API that adapters provide has changed somewhat, the [new standards](https://codecompanion.olimorris.dev/extending/adapters#handler-structure) are fairly straight forward, and there's a note that adapters that provide the old interface will still work, as the plugin automatically maps things around.

Unfortunately, that doesn't go the other way, and so if we try to use codecompanion-history.nvim with an adapter that only provides the new interface, things break:

```
vim.schedule callback: ...ua/codecompanion/_extensions/history/title_generator.lua:257: attempt to call field 'chat_output' (a nil value)
stack traceback:
	...ua/codecompanion/_extensions/history/title_generator.lua:257: in function 'cb'
	.../nvim/lazy/codecompanion.nvim/lua/codecompanion/http.lua:371: in function <.../nvim/lazy/codecompanion.nvim/lua/codecompanion/http.lua:368>
```

This happens with the openai_responses adapter.

### PR DESCRIPTION
**Pull request by xhebox**
## Related Issue(s)

close #62 

## Checklist

- [ ] I've read the [contributing](https://github.com/ravitemer/codecompanion-history.nvim/blob/main/CONTRIBUTING.md) guidelines and have adhered to them in this PR
- [ ] I've updated the README and/or relevant docs pages
- [ ] I've run `make test` to ensure all tests pass
- [ ] I've run `make format` to format the code
- [ ] I've run `make docs` to update the vimdoc pages

### CODE REVIEW

File: lua/codecompanion/_extensions/history/title_generator.lua [hunk 1]
```diff
@@ -254,7 +255,12 @@ function TitleGenerator:_make_adapter_request(chat, prompt, callback)
                 return callback(nil)
             end
             if data then
-                local result = _adapter.handlers.chat_output(_adapter, data)
+                local result = nil
+                if _adapter.handlers.chat_output then
+                    result = _adapter.handlers.chat_output(_adapter, data)
+                else
+                   result = adapters.call_handler(_adapter, "parse_chat", data)
```
Comment (xhebox) [inline lua/codecompanion/_extensions/history/title_generator.lua:262]: @ravitemer oops, the indention here is wrong... It got merged too quick
